name: 'Nelify Deploy'
author: 'Jo Colina'
description: 'Netlify Deploy'

inputs:
  NETLIFY_AUTH_TOKEN:
    description: 'Auth token to use with netlify'
    required: true
    default: ''

  build_directory:
    description: 'Directory where built files are stored'
    required: true
    default: 'build'

  functions_directory:
    description: 'Directory where built files are stored'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.NETLIFY_AUTH_TOKEN }}
    - ${{ inputs.build_directory }}
    - ${{ inputs.functions_directory }}

branding:
  icon: activity
  color: blue
